spring.application.name=idwallet-be
spring.application.name=idwallet-be
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/idwallet}
spring.datasource.username=${DATABASE_USERNAME:idwallet}
spring.datasource.password=${DATABASE_PASSWORD:idwallet}
spring.flyway.enabled=${FLYWAY_ENABLED:false}
management.endpoints.web.exposure.include=health,info,metrics
